name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building ${{ github.ref }} (${{ github.sha }}) for prod"

      - name: Deploy to prod
        run: echo "Deploying ${{ github.ref }} (${{ github.sha }}) to prod environment"
