name: Deploy to Prod
run-name: Deploy to Prod - ${{ github.ref_name }}

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: prod
